import "./globals.css";
import Loader from "./components/Loader";

export const metadata = {
  title: "Portfolio - Ritesh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-screen flex flex-col bg-[#00020f] text-gray-200">
        {/* <Loader /> */}
        {children}
      </body>
    </html>
  );
}
